### ISSUE TITLE
LFG eye resize

### ISSUE THREAD

**Issue by Nasacrim** [teelolws/EditModeExpanded#100]
![image_2023-05-25_165910964](https://github.com/teelolws/EditModeExpanded/assets/134632038/c6f22438-7330-443c-8010-2c0c92e6140e)

The resize bar for the LFG icon went missing. Used to be there, now i havent found a way to resize the icon.

**Comment by Piskemannen** [comment]
I got same problem.

**Comment by teelolws** [comment]
Hey. Since 10.1, the LFG Eye can now be resized in the base UI! The option is under the options for your micro menu:

![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/35529407-f1e6-4a0a-a3ca-d4a4eed4cd9c)

I've removed support from the addon so that we aren't just copying the same work.

**Comment by Nasacrim** [comment]
I see!!! I had the feeling I just couldnt find it, thank you.
