### ISSUE TITLE
Minimap too wide

### ISSUE THREAD

**Issue by Piskemannen** [teelolws/EditModeExpanded#119]
So this problem still persists, reinstall doesn't fix it.

![Minimap](https://github.com/teelolws/EditModeExpanded/assets/133789008/296487f1-7702-4ec8-967e-b7908a541076)

**Comment by teelolws** [comment]
Due to persistent issues with it, I'm going to turn off the minimap header support by default. Turn it back on via options if you want to keep using it:
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/01da1d4c-1a0b-4731-b692-e309aac3f566)

If you have the size of the Minimap smaller than 100%, I can't make that box smaller. This is with the addon turned off and the Minimap set to 60%:
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/fe107a24-4e82-4a88-b472-027c4ac963eb)

The base UI puts that extra padding to the sides of it, and won't let it be dragged off the screen. Unfortunately I cannot stop the base UI doing this without causing more problems.

**Comment by Piskemannen** [comment]
Thanks! Works like before now.
