### ISSUE TITLE
Request: Show frame only during mouseover

### ISSUE THREAD

**Issue by teelolws** [teelolws/EditModeExpanded#16]
What about an option that hides the frame but show it once you hover over it? Similar to the way Bartender do it?

_Originally posted by @Nillx in https://github.com/teelolws/EditModeExpanded/issues/5#issuecomment-1302870058_

Update: Won't be implemented. See other comments for alternatives!

**Comment by PhenomDevel** [comment]
Hey there. I made an addon which makes just that. Since i like EditModeExtended i also added the newly created frames to the mouseover fade options. You might want to take a look: https://www.curseforge.com/wow/addons/blizzhudtweaks

It also provides options to fade based on different character states (in combat, out of combat, rested area, has target).

**Comment by teelolws** [comment]
@PhenomDevel A couple things about what you've done

    if IsAddOnLoaded("EditModeExpanded") then
      frameMapping["MicroButtonAndBagsBarMovable"] = MicroButtonAndBagsBarMovable
      frameMapping["EditModeExpandedBackpackBar"] = EditModeExpandedBackpackBar
      frameMapping["DurabilityFrame"] = DurabilityFrame
      frameMapping["VehicleSeatIndicator"] = VehicleSeatIndicator

Rather than IsAddOnLoaded, since EME is a library, I think a better check would be:

    if LibStub and LibStub.libs["EditModeExpanded-1.0"] and MicroButtonAndBagsBarMovable and and LibStub["EditModeExpanded-1.0"].IsRegistered and LibStub["EditModeExpanded-1.0"]:IsRegistered(MicroButtonAndBagsBarMovable) then

Not as nice as IsAddOnLoaded, but this way it should work with another addon that uses the EME library to handle the menu bar, such as Shadowlands Micro Menu https://github.com/teelolws/SLMicroMenu

I'll add that `IsRegistered` function in the next patch.

You shouldn't need to check for the existence of the Backpack bar as its creation is automatically done when the micro menu bar is registered.

Also, why do you register the durability frame and vehicle frame only if EME is running? Those frames exist even without EME. All I did was added the ability to move them.

**Comment by PhenomDevel** [comment]
Hey,
thanks for the feedback.

I'll remove DurabilityFrame and VehicleSeatIndicator from the additional frames since like you mentioned they're default ui frames.

Also I'll use the LibStub functions to check for the existence of EME and use this to iterate the additional frames once the `IsRegistered` function is existing.

> You shouldn't need to check for the existence of the Backpack bar as its creation is automatically done when the micro menu bar is registered.
Since the code might be very well used for another library i don't want to make assumptions about which frames is created automatically and which is not. I don't think it is much overhead and prevents any lua errors by mistake.

**Comment by teelolws** [comment]
Well, I mean... if `MicroButtonAndBagsBarMovable` exists, and `LibStub["EditModeExpanded-1.0"]:IsRegistered(MicroButtonAndBagsBarMovable)` returns true, but `EditModeExpandedBackpackBar` has been created by some other addon, then I'm going to have bigger issues. Starting with why some other addon is using my variable name!
