### ISSUE TITLE
Addon Keeps Trying To Set The Position Of The Pet Frame During Combat

### ISSUE THREAD

**Issue by lotsoftoons** [teelolws/EditModeExpanded#29]
6x [ADDON_ACTION_BLOCKED] AddOn 'EditModeExpanded' tried to call the protected function 'PetFrame:SetPoint()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@Interface/AddOns/EditModeExpanded/libs/EditModeExpanded-1.0-16/EditModeExpanded-1.0.lua"]:359: in function `RegisterFrame'
[string "@Interface/AddOns/EditModeExpanded/EditModeExpanded.lua"]:133: in function <...terface/AddOns/EditModeExpanded/EditModeExpanded.lua:40>

**Comment by teelolws** [comment]
Is this if you login while in combat? Thats the only way I can see this being possible.

**Comment by lotsoftoons** [comment]
I thought so, but it's happening after I reload out of combat.

**Comment by lotsoftoons** [comment]
I go into combat and eventually I get this error.

**Comment by lotsoftoons** [comment]
It started with yesterdays update.

**Comment by lotsoftoons** [comment]
I think it happens when I summon Xuen.

**Comment by teelolws** [comment]
Okay, this update should fix it. However, because I can't move it in combat, this means that the first time you summon a pet per login, the Pet Frame will be in the default position under your character until you leave combat, then it will move to the spot the you've told the addon to move it to - if you've set a spot, that is.
