### ISSUE TITLE
Consecration timer not showing up underneath portrait as Protection Paladin

### ISSUE THREAD

**Issue by james5272** [teelolws/EditModeExpanded#42]
It only doesn't show up when this addon is enabled, I checked the edit mode settings and none of them have this as an interactable option so maybe that's why it isn't showing up?  Not sure.

**Comment by teelolws** [comment]
Look for "Totem Frame", thats what the Consecreation timer uses. If its disappeared, use the reset button for the Totem Frame!

**Comment by james5272** [comment]
Oh okay, yeah I hit reset and saw it's putting it in the far bottom left as default rather than right under the portrait like it does without the addon.

Here's another one: The experience bar, when unchecked, does not appear for most of my characters.  However for one, my warlock, even with experience bar unchecked it is still appearing.  This is using the same addons and Edit Mode profile as the other characters.  Trying to reset it and then uncheck it again doesn't hide it for this character.

**Comment by teelolws** [comment]
> it's putting it in the far bottom left as default

Yeah this is because the frame was hidden and didn't have a size when the game was first loaded - which means the addon didn't know where it originally was, so puts it to the bottom left corner. From there you can move it to where it should be.

The "unchecking" of the experience bar does not mean it'll hide it. Thats just a way to not show the Selection box during Edit Mode. It works the same way as the checkboxes for the other Blizzard frames.

I'll add the option to Hide the experience bar.

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/202921626-372e7887-dbcd-48ce-a727-d0ad5cbf79a2.png)
![image](https://user-images.githubusercontent.com/49792789/202921630-bbf7620e-e8df-465f-b7d2-5f57e6e92214.png)
