### ISSUE TITLE
Request : add top of screen information to move

### ISSUE THREAD

**Issue by Hermonii** [teelolws/EditModeExpanded#47]
Hi, 
Something that could be really nice to add to move is the yellow information that appear in top of the screen like pvp flag information, or what we could see during some dungeon (like cavern of time that tell us portals).

I hope it's possible and you could add it in a future patch <3

**Comment by teelolws** [comment]
Done. Because it doesn't have a consistent size, you won't be able to reposition it unless you're in an area that causes the subzone information to actually show something. Otherwise it'll just show as an unclickable dot.

See:
![image](https://user-images.githubusercontent.com/49792789/203661389-5019607c-c3df-42ec-b278-b419cb27451f.png)

Vs:
![image](https://user-images.githubusercontent.com/49792789/203661407-7be79443-3f41-4811-835b-9257b7689884.png)

Because of this confusion, I'm setting it to disabled by default. You will need to go into your addon options to turn it on.
![image](https://user-images.githubusercontent.com/49792789/203661618-1701b467-557c-4043-a4ec-ee40d338f4a8.png)
