### ISSUE TITLE
Suggestion: Quest tracker, frames coordinates (x, y) and currently missing UI elements

### ISSUE THREAD

**Issue by antarek** [teelolws/EditModeExpanded#66]
Addon version:10.0.042
Client version: 10.0.2 (french language)

First things first, thanks for your work on this fantastic addon.

A couple other addons also focus on moving Blizzard UI.

Yours has many interesting features such as the ability to move frames using directional keys but yet it misses one major features when it comes to positioning frames. This key feature is the ability to position frames using their 'x, y' coordinates on screen.

Also the Blizzard quest tracker doesn't seem to be supported right now.
![image](https://user-images.githubusercontent.com/42368527/213906670-d61999bf-2fa1-485c-9ed3-81bca9e1358d.png)

Last but not least many UI elements aren't listed among the 'Expanded' panel while still being editable. this is probably not comming from the addon end nontheless it would be better to have them supported and listed.
![image](https://user-images.githubusercontent.com/42368527/213906784-9d86f15d-f759-4d52-ab6e-aa940f21ed52.png)

**Comment by teelolws** [comment]
You can add coordinate support through interface options. It is off by default due to the clutter:
![image](https://user-images.githubusercontent.com/49792789/213907132-cc4f96d9-ff2b-4aa1-a6f3-90ff01f069d7.png)

I don't know why your quest tracker has no options. This is what I see when I click on it:
![image](https://user-images.githubusercontent.com/49792789/213907173-b4ea14c8-2b1d-4db6-9270-e9d3596d8266.png)

Those other elements you are seeing, that aren't part of the "Expanded" panel, are all elements that are part of the default UI. You can move them without this addon. With a few exceptions, this addon doesn't change most of them.

**Comment by antarek** [comment]
Thanks for the clarification.
Regarding the quest tracker issue i m about sure that i also had the same panel than the one that you show on your screenshot the first time that i clicked on the quest tracker. Then after clicking on 'reset to default position' it turned into what i show on my screenshot.

**Comment by teelolws** [comment]
Yeah I'm getting that too. If I then move the quest tracker slightly, the Height option comes back. Its a bug on Blizzards end, unrelated to my addon.

10.0.5 is releasing in 2-3 days, and the XP bar will become handled by Blizzard. I've already pushed code to update the addon around this, so at this point, we should just wait for the patch.

**Comment by antarek** [comment]
Alright, thanks a lot. 👍
