### ISSUE TITLE
[Rquest]Resizable reputation bar

### ISSUE THREAD

**Issue by Revnn** [teelolws/EditModeExpanded#80]
Hey, would it be possible to make the reputation bar resizable just like the exp bar?
Thanks.

**Comment by teelolws** [comment]
Because of the weird way Blizzard handles that Reputation Bar, if you're already max level, the reputation bar actually gets moved into the Experience Bar. The only time you ever actually see that separate Reputation Bar that you can set in Edit Mode is if you're below max level. Do you actually track a Reputation when below max level?

**Comment by Revnn** [comment]
I actually only track reputation on my leveling alts, i like to level through dungeon and getting SW/ORG reputation in order to buy the flight skill for a cheaper price

**Comment by teelolws** [comment]
Behaves weirdly with the reputation and experience bar when artifact power gets slotted in there. Need to fix: 
![image](https://user-images.githubusercontent.com/49792789/227768968-56c2f5eb-426a-4a92-8c5d-6322c463e8d1.png)
![image](https://user-images.githubusercontent.com/49792789/227769006-7ab6acea-aa52-4c20-a3ce-58d89067e11d.png)

**Comment by Etern213** [comment]
> Behaves weirdly with the reputation and experience bar when artifact power gets slotted in there. Need to fix:

I was thinking about add a option to control the width and height of a widget, scale setting sometimes too limiting. I think some widget better to set its size not scale.
