### ISSUE TITLE
[Request] Moveable bonus roll widget

### ISSUE THREAD

**Issue by olioster** [teelolws/EditModeExpanded#84]
I know it's not used anymore but can we get the option to move the bonus roll widget that shows up in older raids?

**Comment by teelolws** [comment]
This should add support. You will only be able to move it after you have triggered a bonus roll since the last time you logged in or did a /reload, this is for two reasons:
1. To reduce clutter during edit mode, and
2. Because the Bonus Roll frame is not properly setup until you actually get loot that triggers a bonus roll, so there won't be anything to show during Edit Mode
