### ISSUE TITLE
Raid frame addon blocked

### ISSUE THREAD

**Issue by teelolws** [teelolws/EditModeExpanded#96]
Something to do with magnetism to the raid frame manager, maybe?

**Comment by Piskemannen** [comment]
Hey again, do you have a list of things you plan to add to this great addon? I have some ideas, but if I knew more about coding/UI elements, I wouldn't suggest something that needs rework of an entire frame... 

One that comes to mind is square portrait instead of the round one, unsure if it's as easy as when you made square minimap an option?

**Comment by teelolws** [comment]
Yeah a square portrait would require an entire rework, thats something better left for another addon. Theres probably one out there somewhere!
